#projDir: E:\Desktop\code\wyyy\demo\src
projDir: E:\Desktop\code\wm\demo\src\main\java\com\example\demo
packageName: com.example.demo
className: Orders
author: admin
fields:
  - orderNo: String
    userId: Integer
    sellUserId: Integer
    status: Integer
    amount: Double
