#projDir: E:\Desktop\code\wyyy\demo\src
projDir: E:\Desktop\code\fruitmgr\backend\src\main\java\com\h2bus\backend
packageName: com.h2bus.backend
className: Example
author: admin
fields:
  - name: String
    title: String